#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/207543f7-b910-40be-a7b5-fcadd09fe9ff/ # 
title: numberveifyapi
securitySchemes:
  OAuth:
    type: OAuth 2.0
    description: OAuth 2.0
    displayName: OAuth 2.0
  basic:
    type: Basic Authentication
    displayName: Basic Authentication
    description: API only works with Basic Authentication
protocols: 
- HTTP
description: NumVerify offers a full-featured yet simple RESTful JSON API for national and international phone number validation and information lookup for a total of 232 countries around the world.
documentation:
  - title: NumVerify API
    content: Refer below content for more information
             https://numverify.com/documentation
types:
  apiresponse:
    properties:
      valid: boolean
      number: string
      local_format: string
      international_format: string
      country_prefix: string
      country_code: string
      country_name: string
      location: string
      carrier: string
      line_type: string
/validate:
  get: 
    queryParameters:
      access_key: string
      number: string
      country_code: string
      format: string
    description: for validating the phone number
    displayName: validate phone
    protocols:
      - HTTP
    responses:
      200:
        body:
          application/json:
            type: apiresponse
            example:
              {
                 "valid": true,
                 "number": "14158586273",
                 "local_format": "4158586273",
                 "international_format": "+14158586273",
                 "country_prefix": "+1",
                 "country_code": "US",
                 "country_name": "United States of America",
                 "location": "Novato",
                 "carrier": "AT&T Mobility LLC",
                 "line_type": "mobile"
              } 
      400:
        body:
          application/json:
            properties:
              message: string
            example:
              {message: "API Key is invalid"}
      403:
        body:
          application/json:
            properties:
              message: string
            example:
              {message: "Invalid URL"}

              
            
